export interface OpenOrder {
    id: string,
    chainId: number,
    nonce: number, 
    makerAsset: string,
    takerAsset: string,
    contractAddress: string,
    orderHash: string,
    makerAssetSymbol: string,
    takerAssetSymbol: string,
    makerAssetLogoUrl: string,
    takerAssetLogoUrl: string,
    makerAssetDecimals: number,
    takerAssetDecimals: number,
    makingAmount: string,
    takingAmount: string,
    filledMakingAmount: string,
    filledTakingAmount: string,
    status: string,
    createdAt: number,
    expiredAt: number,
    operatorSignatureExpiredAt: number,
    transactions: object[]
}