export interface Order {
    id: string,
    chainId: string,
    signature: string,
    salt: string,
    makerAsset: string,
    takerAsset: string,
    maker: string,
    contractAddress: string,
    receiver: string,
    allowedSenders: string,
    makingAmount: string,
    takingAmount: string,
    filledMakingAmount: string,
    filledTakingAmount: string,
    feeConfig: string,
    feeRecipient: string,
    makerTokenFeePercent: string,
    makerAssetData: string,
    takerAssetData: string,
    getMakerAmount: string,
    getTakerAmount: string,
    predicate: string,
    interaction: string,
    expiredAt: number
}